/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/singup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/artists`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/artists/shows-map`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/playlist`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/playlist/search`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/songs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/artists/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/tabs/playlist/[playlistId]`, params: Router.UnknownInputParams & { playlistId: string | number; } } | { pathname: `/tabs/songs/[albumId]`, params: Router.UnknownInputParams & { albumId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/singup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/player`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/artists`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/artists/shows-map`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/playlist`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/playlist/search`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/songs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/artists/[artistId]`, params: Router.UnknownOutputParams & { artistId: string; } } | { pathname: `/tabs/playlist/[playlistId]`, params: Router.UnknownOutputParams & { playlistId: string; } } | { pathname: `/tabs/songs/[albumId]`, params: Router.UnknownOutputParams & { albumId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/singup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/player${`?${string}` | `#${string}` | ''}` | `/tabs/artists${`?${string}` | `#${string}` | ''}` | `/tabs/artists/shows-map${`?${string}` | `#${string}` | ''}` | `/tabs/favorites${`?${string}` | `#${string}` | ''}` | `/tabs/playlist${`?${string}` | `#${string}` | ''}` | `/tabs/playlist/search${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | `/tabs/songs${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/singup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/artists`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/artists/shows-map`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/playlist`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/playlist/search`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/songs`; params?: Router.UnknownInputParams; } | `/tabs/artists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tabs/playlist/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tabs/songs/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/tabs/artists/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/tabs/playlist/[playlistId]`, params: Router.UnknownInputParams & { playlistId: string | number; } } | { pathname: `/tabs/songs/[albumId]`, params: Router.UnknownInputParams & { albumId: string | number; } };
    }
  }
}
